apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  # Gateway resources
  # NOTE: GatewayClass "cilium" is created by the Cilium Helm chart when Gateway API is enabled.
  # Keeping it here causes Argo CD SharedResourceWarning because two Applications manage the same object.
  # - gateway-class.yaml
  - ns.yaml
  - issuer-selfsigned.yaml
  - cert-starbase.yaml
  - gw-external.yaml
  - gw-internal.yaml



generatorOptions:
  disableNameSuffixHash: true