apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - http-route.yaml
  - projects.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 9.3.4 # renovate: datasource=helm depName=argo-cd repository=https://argoproj.github.io/argo-helm
    releaseName: "argocd"
    namespace: argocd
    valuesFile: values.yaml
