apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml

helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.12.2 # renovate: datasource=helm depName=metrics-server repository=https://kubernetes-sigs.github.io/metrics-server/
    releaseName: metrics-server
    namespace: kube-system
    valuesFile: values.yaml
