apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  settings.yaml: |
    title: Starbase HomeLab
    favicon: https://kubernetes.io/images/favicon.png
    theme: dark
    color: slate
    headerStyle: boxed
    layout:
      Infrastructure:
        style: row
        columns: 3
      Applications:
        style: row
        columns: 3

  bookmarks.yaml: |
    - Developer:
        - GitHub:
            - abbr: GH
              href: https://github.com/Tanmay95/Kubernetes-homelab
        - Kubernetes Docs:
            - abbr: K8s
              href: https://kubernetes.io/docs/

  services.yaml: |
    - Infrastructure:
        - ArgoCD:
            icon: argocd.png
            href: https://argocd.starbasestudio.uk
            description: GitOps CD
            namespace: argocd
            app: argocd-server
            widget:
              type: argocd
              url: https://argocd-server.argocd.svc.cluster.local
              key: {{HOMEPAGE_VAR_ARGOCD_API_KEY}}
        - Hubble UI:
            icon: cilium.png
            href: https://hubble.starbasestudio.uk
            description: Network Observability
        - Proxmox:
            icon: proxmox.png
            href: https://192.168.1.10:8006
            description: Hypervisor

    - Applications:
        - Podinfo:
            icon: https://raw.githubusercontent.com/stefanprodan/podinfo/gh-pages/cuddle_bunny.gif
            href: http://podinfo.starbasestudio.uk
            description: Demo Application
            namespace: podinfo
            app: podinfo

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Starbase Cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23

  kubernetes.yaml: |
    mode: cluster

  docker.yaml: ""
