apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - http-route.yaml
  - configmap.yaml

helmCharts:
  - name: homepage
    repo: https://jameswynn.github.io/helm-charts
    version: 2.0.1 # renovate: datasource=helm depName=homepage repository=https://jameswynn.github.io/helm-charts
    releaseName: homepage
    namespace: homepage
    valuesFile: values.yaml
