apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - http-route.yaml
  - hpa.yaml

helmCharts:
  - name: podinfo
    repo: https://stefanprodan.github.io/podinfo
    version: 6.7.1 # renovate: datasource=helm depName=podinfo repository=https://stefanprodan.github.io/podinfo
    releaseName: podinfo
    namespace: podinfo
    valuesFile: values.yaml
