apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - secret.yaml
  - deployment-db.yaml
  - deployment.yaml
  - deployment-importer.yaml
  - service.yaml
  - httproute.yaml

namespace: firefly-iii
