apiVersion: v1
kind: Service
metadata:
  name: firefly-iii-db
  namespace: firefly-iii
  labels:
    app.kubernetes.io/name: firefly-iii-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: firefly-iii-db
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-iii
  namespace: firefly-iii
  labels:
    app.kubernetes.io/name: firefly-iii
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: firefly-iii
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-iii-importer
  namespace: firefly-iii
  labels:
    app.kubernetes.io/name: firefly-iii-importer
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: firefly-iii-importer
